In [76]:
from sqlalchemy import create_engine
import pandas as pd 
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [79]:
users_path = '/Users/fuwang/Documents/Project/Bilibili User Analysis/data/users.csv'

In [80]:
df1 = pd.read_csv(users_path)

In [81]:
df1.head()

,mid,name,sex,fans,friend,current_level,archive_count,like_num,sign,vip_type,vip_date,vip_status,Official_role,Official_title
0,429392011,天天鉴宝,保密,1600639,23,6,3376,33314802,+公众号【天天鉴宝app】回复“3”可加入宝友粉丝群\n短视频合作vx：739800914 ...,2,2022/11/17 00:00:00,1,0,NaN
1,691250144,5-MinuteCrafts中文,保密,321869,9,6,397,708116,YouTube最大的DIY手工频道5-MinuteCrafts，超酷的DIY&生活小妙招！,0,1970/1/1 08:00:00,0,2,5-MinuteCrafts官方账号
2,521689911,魔术特白,男,263403,23,6,781,3205844,有合作+ mohuanlaobai 即“魔幻老白”拼音。,2,2023/6/17 00:00:00,1,1,bilibili 知名UP主
3,441984834,魔术趣玩方信,保密,21261,38,5,464,382909,简单魔术教学。一学就会B站的朋友都特别友好，有些评论弹幕没一一回复到，也谢谢投币的朋友。感谢...,2,2022/11/3 00:00:00,1,0,NaN
4,483052036,老大南,男,201261,115,6,299,2028356,大南实验室欢迎大家创意投稿！\n商务合作直接私信！,1,2021/4/24 00:00:00,0,1,bilibili 知名UP主

In [82]:
df1.shape

(238299, 14)

In [83]:
df1.describe()

,mid,fans,friend,current_level,archive_count,like_num,vip_type,vip_status,Official_role
count,2.382990e+05,2.382990e+05,238299.000000,238299.000000,238299.000000,2.382990e+05,238299.000000,238299.000000,238299.000000
mean,3.066376e+08,4.751854e+03,168.117818,3.900289,77.429536,2.922663e+04,0.746805,0.276019,0.059039
std,3.750802e+08,7.774559e+04,295.224134,1.576132,779.163713,1.055914e+06,0.806563,0.447262,0.488667
min,1.000000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,2.618739e+07,8.000000e+00,10.000000,3.000000,4.000000,1.800000e+01,0.000000,0.000000,0.000000
50%,2.551708e+08,5.300000e+01,62.000000,4.000000,12.000000,1.270000e+02,1.000000,0.000000,0.000000
75%,4.382657e+08,4.240000e+02,190.000000,5.000000,40.000000,1.173000e+03,1.000000,1.000000,0.000000
max,2.147444e+09,1.074117e+07,2000.000000,6.000000,232650.000000,3.060161e+08,2.000000,3.000000,9.000000

In [46]:
df1.columns

Index(['mid', 'name', 'sex', 'fans', 'friend', 'current_level',
       'archive_count', 'like_num', 'sign', 'vip_type', 'vip_date',
       'vip_status', 'Official_role', 'Official_title'],
      dtype='object')

In [47]:
df1.vip_date = pd.to_datetime(df1.vip_date)

In [48]:
video_path = '/Users/fuwang/Documents/Project/Bilibili User Analysis/data/video.csv'

In [49]:
df2 = pd.read_csv(video_path)

In [50]:
df2.head()

,aid,bvid,copyright,ctime,desc,height,width,duration,dynamic,up_mid,...,tname,videos,coin,danmaku,favorite,his_rank,like,reply,share,view
0,593438728,BV1kq4y1C7xR,1,2022/2/6 17:50:07,需要学习软件，录屏，裸模，笔刷，人体肌肉结构组织等学习资料加QQ群：751687231都可以...,1080,1920,6785,NaN,301714219,...,野生技能协会,1,0,0,0,0,0,0,0,1
1,296270310,BV1xF411J7Gu,1,2022/2/6 17:49:42,（背景图片来自网络，侵删）,1080,1440,26,有一说一如果有人跟我用这首诗表白我就心动了٩(๑ơలơ)۶♡\n呸，我在想peach,440498711,...,野生技能协会,1,0,0,0,0,1,1,0,1
2,893387969,BV1vP4y1P7rw,1,2022/2/6 17:49:06,NaN,1080,1920,8117,NaN,521313967,...,野生技能协会,1,0,0,0,0,0,0,0,0
3,678786611,BV1Sm4y1o7kK,2,2022/2/6 17:48:36,https://youtu.be/Glbaeml40DQ\n原作者：Tiff In Tech...,1080,1920,367,进来学习,600284689,...,野生技能协会,1,1,4,1,0,2,0,0,1
4,681355833,BV1jS4y1G7Jn,1,2022/2/6 17:47:43,郎溪首条跨省公交溧阳196路（社渚至梅渚）全程15分钟，10公里，票价2元。,1920,1080,825,NaN,397379442,...,野生技能协会,1,0,0,0,0,0,0,0,1

In [51]:
df2.shape

(2173885, 25)

In [52]:
df2.describe()

,aid,copyright,height,width,duration,up_mid,rights_is_cooperation,tid,videos,coin,danmaku,favorite,his_rank,like,reply,share,view
count,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06,2.173885e+06
mean,3.783526e+08,1.198958e+00,9.542611e+02,1.522237e+03,3.632818e+03,3.784930e+08,3.546646e-04,1.220002e+02,3.356654e+00,3.820375e+01,1.876502e+01,1.195111e+02,5.713812e-01,1.049674e+02,1.118972e+01,1.453170e+01,4.362967e+03
std,3.227848e+08,3.992165e-01,3.693055e+02,6.053191e+02,1.951610e+04,4.286555e+08,1.882920e-02,1.180210e-01,1.504677e+01,1.380367e+03,1.581532e+03,2.139068e+03,1.885052e+01,2.659605e+03,9.247087e+01,3.407207e+02,5.844175e+04
min,2.152750e+05,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01,0.000000e+00,1.220000e+02,1.000000e+00,0.000000e+00,0.000000e+00,-4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00
25%,6.386990e+07,1.000000e+00,7.200000e+02,1.116000e+03,9.700000e+01,4.845222e+07,0.000000e+00,1.220000e+02,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,6.000000e+01
50%,3.299539e+08,1.000000e+00,1.080000e+03,1.774000e+03,3.360000e+02,3.226456e+08,0.000000e+00,1.220000e+02,1.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,1.000000e+00,2.480000e+02
75%,6.734597e+08,1.000000e+00,1.080000e+03,1.920000e+03,1.158000e+03,4.754290e+08,0.000000e+00,1.220000e+02,1.000000e+00,5.000000e+00,1.000000e+00,2.300000e+01,0.000000e+00,1.700000e+01,4.000000e+00,5.000000e+00,1.118000e+03
max,9.788742e+08,2.000000e+00,7.296000e+03,1.078600e+04,2.710223e+06,2.147444e+09,1.000000e+00,2.100000e+02,1.000000e+03,8.611460e+05,2.029014e+06,9.279220e+05,1.000000e+03,9.336900e+05,2.501400e+04,2.252330e+05,1.577385e+07

In [53]:
df2.columns

Index(['aid', 'bvid', 'copyright', 'ctime', 'desc', 'height', 'width',
       'duration', 'dynamic', 'up_mid', 'up_name', 'pubdate',
       'rights_is_cooperation', 'tid', 'title', 'tname', 'videos', 'coin',
       'danmaku', 'favorite', 'his_rank', 'like', 'reply', 'share', 'view'],
      dtype='object')

In [54]:
df2.ctime = pd.to_datetime(df2.ctime)
df2.pubdate = pd.to_datetime(df2.pubdate)

In [55]:
df2[df2['ctime'].dt.year == 2017]

,aid,bvid,copyright,ctime,desc,height,width,duration,dynamic,up_mid,...,tname,videos,coin,danmaku,favorite,his_rank,like,reply,share,view
105872,6070754,BV18s41167KD,1,2017-06-14 18:42:28,AE导出渲染出了点毛病QAQ，然而up主已经跪了,360,640,900,NaN,38970427,...,野生技能协会,1,17,2,65,0,42,0,13,1219
334967,3866054,BV1gs41197SR,2,2017-06-14 17:31:39,NaN,360,480,250,NaN,13656366,...,野生技能协会,1,1,0,5,0,3,0,0,52
740793,7333053,BV17s411s7Gg,1,2017-06-14 18:46:12,【装逼机车王】警察查水表系列,360,640,903,NaN,43113791,...,野生技能协会,1,0,0,1,0,0,0,0,6
858450,1893000,BV1Rx411w7MU,2,2017-06-13 20:10:42,Linecg 虽然是R13的，但是也是从最基础的讲起，R16的也可以看看。还算比较详细，比较...,360,640,22723,NaN,24268,...,野生技能协会,27,4,13,102,0,3,4,10,1562
911761,10326045,BV17x411m7md,1,2017-06-14 19:08:08,leetcode solution,360,640,583,NaN,108657656,...,野生技能协会,1,0,0,1,0,0,0,0,162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173880,230603,BV1ix411w7qb,2,2017-06-14 12:29:03,［周年特辑－视频是怎么炼成的 ］相信一会就能看了。纪录了Razr视频的整个经过，也是现在我制...,360,638,1652,NaN,286649,...,野生技能协会,1,3,19,28,0,3,5,13,1772
2173881,229127,BV1sx411w7nn,2,2017-06-14 03:10:36,原创 之前的传送门av215275，说好的原理解说，其实是很简单的玩意，儿。欢迎@阿婆主渣浪...,288,512,245,NaN,124473,...,野生技能协会,1,1,193,20,709,0,8,13,8923
2173882,222443,BV1Wx411w74S,2,2017-06-14 02:18:32,shareyoucan.com是PengTitus彭老师创建的以网络讲演方式推广环保教育的网...,240,320,2399,NaN,109939,...,野生技能协会,7,9,115,234,0,7,10,18,9008
2173883,221991,BV1sx411w7A5,2,2017-06-13 23:38:18,youku youtube,336,448,105,NaN,64008,...,野生技能协会,3,7,584,213,98,8,64,13,90773
2173884,215275,BV1nx411w7kd,2,2017-06-14 03:10:36,原创 简介嘛……这个是我做来玩的，顺便撩妹子。画面有点奇怪，应该是没有压制好。P2是以前测试...,288,512,336,NaN,124473,...,野生技能协会,2,1,147,21,637,1,16,14,10349

In [56]:
password = '1234567'

In [64]:
class MySQLUtil:
    # param：ip、port、username、password、database、tableName
    def __init__(self, host, port, username, password, db, table):
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.db = db
        self.table = table
        self.write_mode = 'append'
        self.connect_url = 'mysql+pymysql://' + username + ':' + password + '@' + host + ':' + port + '/' + db + '?charset=utf8mb4'
        self.mysql_connect = create_engine(self.connect_url)
 
    def df_write_mysql(self, data):
        pd.io.sql.to_sql(data, self.table, self.mysql_connect, schema=self.db, if_exists=self.write_mode,index=False,chunksize=10000)
        print ("write into mysql finish")
    def get_info(self,sql):
        data=pd.read_sql_query(sql,self.mysql_connect)
        return data

In [69]:
conx1 = MySQLUtil("localhost","3306","root",password,"BBUser","users")

In [70]:
conx1.df_write_mysql(df1)

write into mysql finish

In [71]:
conx2 = MySQLUtil("localhost","3306","root",password,"BBUser","video")

In [72]:
conx2.df_write_mysql(df2)

write into mysql finish